-- ══════════════════════════════════════════════════════════
-- DMS (Document Management System) 테이블
-- ══════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS DMS_FOLDER (
    FOLDER_SEQ  BIGINT       NOT NULL AUTO_INCREMENT,
    FAMILY_ID   VARCHAR(50)  NOT NULL COMMENT '가족 ID',
    FOLDER_NM   VARCHAR(200) NOT NULL COMMENT '폴더명',
    PARENT_SEQ  BIGINT       NULL     COMMENT '부모 폴더 SEQ (NULL=루트)',
    SORT_ORDER  INT          NOT NULL DEFAULT 0,
    REG_ID      VARCHAR(50)  NULL,
    REG_DT      DATETIME     NOT NULL DEFAULT NOW(),
    UPD_ID      VARCHAR(50)  NULL,
    UPD_DT      DATETIME     NOT NULL DEFAULT NOW(),
    PRIMARY KEY (FOLDER_SEQ),
    INDEX IDX_DMS_FOLDER_FAMILY (FAMILY_ID),
    INDEX IDX_DMS_FOLDER_PARENT (PARENT_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='DMS 폴더';

CREATE TABLE IF NOT EXISTS DMS_FILE (
    FILE_SEQ    BIGINT       NOT NULL AUTO_INCREMENT,
    FAMILY_ID   VARCHAR(50)  NOT NULL COMMENT '가족 ID',
    FOLDER_SEQ  BIGINT       NULL     COMMENT '소속 폴더 SEQ (NULL=루트)',
    FILE_NM     VARCHAR(500) NOT NULL COMMENT '원본 파일명',
    STORED_NM   VARCHAR(500) NOT NULL COMMENT '저장 파일명 (UUID)',
    FILE_SIZE   BIGINT       NOT NULL DEFAULT 0 COMMENT '파일 크기 (bytes)',
    MIME_TYPE   VARCHAR(200) NULL     COMMENT 'MIME 타입',
    REG_ID      VARCHAR(50)  NULL,
    REG_DT      DATETIME     NOT NULL DEFAULT NOW(),
    UPD_ID      VARCHAR(50)  NULL,
    UPD_DT      DATETIME     NOT NULL DEFAULT NOW(),
    PRIMARY KEY (FILE_SEQ),
    INDEX IDX_DMS_FILE_FAMILY   (FAMILY_ID),
    INDEX IDX_DMS_FILE_FOLDER   (FOLDER_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='DMS 파일';
