CREATE TABLE IF NOT EXISTS SNS_POST (
    POST_SEQ    BIGINT       NOT NULL AUTO_INCREMENT,
    FAMILY_ID   VARCHAR(50)  NOT NULL,
    CONTENT     TEXT         NULL,
    REG_ID      VARCHAR(50)  NOT NULL,
    REG_DT      DATETIME     NOT NULL DEFAULT NOW(),
    UPD_DT      DATETIME     NOT NULL DEFAULT NOW(),
    PRIMARY KEY (POST_SEQ),
    INDEX IDX_SNS_POST_FAMILY (FAMILY_ID, REG_DT DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SNS_POST_IMG (
    IMG_SEQ     BIGINT       NOT NULL AUTO_INCREMENT,
    POST_SEQ    BIGINT       NOT NULL,
    FAMILY_ID   VARCHAR(50)  NOT NULL,
    FILE_NM     VARCHAR(500) NOT NULL,
    STORED_NM   VARCHAR(500) NOT NULL,
    SORT_ORDER  INT          NOT NULL DEFAULT 0,
    REG_ID      VARCHAR(50)  NOT NULL,
    REG_DT      DATETIME     NOT NULL DEFAULT NOW(),
    PRIMARY KEY (IMG_SEQ),
    INDEX IDX_SNS_IMG_POST (POST_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SNS_POST_COMMENT (
    COMMENT_SEQ  BIGINT       NOT NULL AUTO_INCREMENT,
    POST_SEQ     BIGINT       NOT NULL,
    FAMILY_ID    VARCHAR(50)  NOT NULL,
    CONTENT      TEXT         NOT NULL,
    REG_ID       VARCHAR(50)  NOT NULL,
    REG_DT       DATETIME     NOT NULL DEFAULT NOW(),
    UPD_DT       DATETIME     NOT NULL DEFAULT NOW(),
    PRIMARY KEY (COMMENT_SEQ),
    INDEX IDX_SNS_COMMENT_POST (POST_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SNS_POST_LIKE (
    POST_SEQ    BIGINT       NOT NULL,
    FAMILY_ID   VARCHAR(50)  NOT NULL,
    REG_ID      VARCHAR(50)  NOT NULL,
    REG_DT      DATETIME     NOT NULL DEFAULT NOW(),
    PRIMARY KEY (POST_SEQ, REG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
