-- =====================================================
-- HOMES 자산관리 테이블 생성 SQL
-- charset: utf8mb4
-- =====================================================

-- 1. 자산 형태 코드 테이블
CREATE TABLE IF NOT EXISTS ASSET_TYPE_CD (
    ASSET_TYPE   VARCHAR(30)  NOT NULL PRIMARY KEY,
    ASSET_TYPE_NM VARCHAR(100) NOT NULL,
    SORT_ORDER   INT          NOT NULL DEFAULT 0,
    USE_YN       CHAR(1)      NOT NULL DEFAULT 'Y',
    REG_DT       DATETIME     NOT NULL DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO ASSET_TYPE_CD (ASSET_TYPE, ASSET_TYPE_NM, SORT_ORDER) VALUES
('CASH',          '현금',             10),
('BANK',          '예금/통장',        20),
('STOCK',         '주식',             30),
('FUND',          '펀드',             40),
('COIN',          '코인',             50),
('HOUSE_DEPOSIT', '집 계약금/보증금', 60),
('CAR',           '자동차',           70),
('REAL_ESTATE',   '부동산',           80),
('PENSION',       '연금',             90),
('ETC',           '기타',             99)
ON DUPLICATE KEY UPDATE ASSET_TYPE_NM = VALUES(ASSET_TYPE_NM);

-- 2. 자산원장 현재 상태 테이블
CREATE TABLE IF NOT EXISTS ASSET_MST (
    ASSET_SEQ      BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FAMILY_ID      VARCHAR(50)  NOT NULL,
    ASSET_NM       VARCHAR(200) NOT NULL,
    ASSET_TYPE     VARCHAR(30)  NOT NULL,
    LIQUID_YN      CHAR(1)      NOT NULL DEFAULT 'Y',
    AMOUNT         BIGINT       NOT NULL DEFAULT 0,
    MEMO           VARCHAR(1000),
    DEL_YN         CHAR(1)      NOT NULL DEFAULT 'N',
    DISPOSE_YN     CHAR(1)      NOT NULL DEFAULT 'N',
    DISPOSE_YMD    DATE,
    DISPOSE_REASON VARCHAR(1000),
    REG_ID         VARCHAR(50),
    REG_DT         DATETIME     NOT NULL DEFAULT NOW(),
    UPD_ID         VARCHAR(50),
    UPD_DT         DATETIME     NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_ASSET_TYPE FOREIGN KEY (ASSET_TYPE) REFERENCES ASSET_TYPE_CD(ASSET_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IF NOT EXISTS IDX_ASSET_MST_FAMILY ON ASSET_MST (FAMILY_ID, DEL_YN, DISPOSE_YN);

-- 3. 대출원장 현재 상태 테이블
CREATE TABLE IF NOT EXISTS LOAN_MST (
    LOAN_SEQ        BIGINT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FAMILY_ID       VARCHAR(50)    NOT NULL,
    LOAN_NM         VARCHAR(200)   NOT NULL,
    LOAN_AMOUNT     BIGINT         NOT NULL DEFAULT 0,
    CURRENT_BALANCE BIGINT         NOT NULL DEFAULT 0,
    INTEREST_RATE   DECIMAL(5,2),
    LOAN_MONTHS     INT,
    START_YMD       DATE,
    END_YMD         DATE,
    MEMO            VARCHAR(1000),
    DEL_YN          CHAR(1)        NOT NULL DEFAULT 'N',
    CLOSE_YN        CHAR(1)        NOT NULL DEFAULT 'N',
    CLOSE_YMD       DATE,
    CLOSE_REASON    VARCHAR(1000),
    REG_ID          VARCHAR(50),
    REG_DT          DATETIME       NOT NULL DEFAULT NOW(),
    UPD_ID          VARCHAR(50),
    UPD_DT          DATETIME       NOT NULL DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IF NOT EXISTS IDX_LOAN_MST_FAMILY ON LOAN_MST (FAMILY_ID, DEL_YN, CLOSE_YN);

-- 4. 반복 현금흐름 계획 테이블 (정기수입/지출 메뉴용 - 이번 화면 구현 대상 아님)
CREATE TABLE IF NOT EXISTS CASH_FLOW_PLAN_MST (
    PLAN_SEQ   BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FAMILY_ID  VARCHAR(50)  NOT NULL,
    PLAN_NM    VARCHAR(200) NOT NULL,
    FLOW_TYPE  VARCHAR(20)  NOT NULL COMMENT 'INCOME/EXPENSE/SAVING/INVEST',
    AMOUNT     BIGINT       NOT NULL DEFAULT 0,
    CYCLE_TYPE VARCHAR(20)  NOT NULL COMMENT 'MONTHLY/YEARLY/ONCE/CUSTOM',
    CYCLE_MONTH INT,
    CYCLE_DAY   INT,
    START_YMD  DATE,
    END_YMD    DATE,
    USE_YN     CHAR(1)      NOT NULL DEFAULT 'Y',
    MEMO       VARCHAR(1000),
    REG_ID     VARCHAR(50),
    REG_DT     DATETIME     NOT NULL DEFAULT NOW(),
    UPD_ID     VARCHAR(50),
    UPD_DT     DATETIME     NOT NULL DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IF NOT EXISTS IDX_CASH_FLOW_FAMILY ON CASH_FLOW_PLAN_MST (FAMILY_ID, USE_YN);

-- =====================================================
-- View 생성
-- =====================================================

-- V_ASSET_SUMMARY: familyId별 자산/부채/현금흐름 요약
CREATE OR REPLACE VIEW V_ASSET_SUMMARY AS
SELECT
    f.FAMILY_ID,
    COALESCE(a.TOTAL_ASSET_AMOUNT,         0) AS TOTAL_ASSET_AMOUNT,
    COALESCE(a.TOTAL_LIQUID_ASSET_AMOUNT,  0) AS TOTAL_LIQUID_ASSET_AMOUNT,
    COALESCE(a.TOTAL_FIXED_ASSET_AMOUNT,   0) AS TOTAL_FIXED_ASSET_AMOUNT,
    COALESCE(a.TOTAL_INVEST_AMOUNT,        0) AS TOTAL_INVEST_AMOUNT,
    COALESCE(l.TOTAL_LOAN_BALANCE,         0) AS TOTAL_LOAN_BALANCE,
    COALESCE(a.TOTAL_ASSET_AMOUNT, 0) - COALESCE(l.TOTAL_LOAN_BALANCE, 0) AS NET_ASSET_AMOUNT,
    COALESCE(cf.MONTHLY_INCOME_AMOUNT,     0) AS MONTHLY_INCOME_AMOUNT,
    COALESCE(cf.MONTHLY_EXPENSE_AMOUNT,    0) AS MONTHLY_EXPENSE_AMOUNT,
    COALESCE(cf.MONTHLY_SAVING_AMOUNT,     0) AS MONTHLY_SAVING_AMOUNT,
    COALESCE(cf.MONTHLY_INVEST_AMOUNT,     0) AS MONTHLY_INVEST_AMOUNT,
    COALESCE(cf.MONTHLY_INCOME_AMOUNT, 0)
        - COALESCE(cf.MONTHLY_EXPENSE_AMOUNT, 0)
        - COALESCE(cf.MONTHLY_SAVING_AMOUNT, 0)
        - COALESCE(cf.MONTHLY_INVEST_AMOUNT, 0) AS EXPECTED_MONTHLY_CASH_FLOW
FROM (SELECT DISTINCT FAMILY_ID FROM ASSET_MST
      UNION
      SELECT DISTINCT FAMILY_ID FROM LOAN_MST
      UNION
      SELECT DISTINCT FAMILY_ID FROM CASH_FLOW_PLAN_MST) f
LEFT JOIN (
    SELECT
        FAMILY_ID,
        SUM(AMOUNT)                                                                      AS TOTAL_ASSET_AMOUNT,
        SUM(CASE WHEN LIQUID_YN = 'Y' THEN AMOUNT ELSE 0 END)                           AS TOTAL_LIQUID_ASSET_AMOUNT,
        SUM(CASE WHEN LIQUID_YN = 'N' THEN AMOUNT ELSE 0 END)                           AS TOTAL_FIXED_ASSET_AMOUNT,
        SUM(CASE WHEN ASSET_TYPE IN ('STOCK','FUND','COIN','PENSION') THEN AMOUNT ELSE 0 END) AS TOTAL_INVEST_AMOUNT
    FROM ASSET_MST
    WHERE DEL_YN = 'N' AND DISPOSE_YN = 'N'
    GROUP BY FAMILY_ID
) a ON f.FAMILY_ID = a.FAMILY_ID
LEFT JOIN (
    SELECT
        FAMILY_ID,
        SUM(CURRENT_BALANCE) AS TOTAL_LOAN_BALANCE
    FROM LOAN_MST
    WHERE DEL_YN = 'N' AND CLOSE_YN = 'N'
    GROUP BY FAMILY_ID
) l ON f.FAMILY_ID = l.FAMILY_ID
LEFT JOIN (
    SELECT
        FAMILY_ID,
        SUM(CASE WHEN FLOW_TYPE = 'INCOME'  AND CYCLE_TYPE = 'MONTHLY' THEN AMOUNT ELSE 0 END) AS MONTHLY_INCOME_AMOUNT,
        SUM(CASE WHEN FLOW_TYPE = 'EXPENSE' AND CYCLE_TYPE = 'MONTHLY' THEN AMOUNT ELSE 0 END) AS MONTHLY_EXPENSE_AMOUNT,
        SUM(CASE WHEN FLOW_TYPE = 'SAVING'  AND CYCLE_TYPE = 'MONTHLY' THEN AMOUNT ELSE 0 END) AS MONTHLY_SAVING_AMOUNT,
        SUM(CASE WHEN FLOW_TYPE = 'INVEST'  AND CYCLE_TYPE = 'MONTHLY' THEN AMOUNT ELSE 0 END) AS MONTHLY_INVEST_AMOUNT
    FROM CASH_FLOW_PLAN_MST
    WHERE USE_YN = 'Y'
    GROUP BY FAMILY_ID
) cf ON f.FAMILY_ID = cf.FAMILY_ID;

-- V_ASSET_TYPE_SUMMARY: familyId + assetType별 현재 자산 합계
CREATE OR REPLACE VIEW V_ASSET_TYPE_SUMMARY AS
SELECT
    a.FAMILY_ID,
    a.ASSET_TYPE,
    t.ASSET_TYPE_NM,
    SUM(a.AMOUNT)  AS TOTAL_AMOUNT,
    COUNT(a.ASSET_SEQ) AS ASSET_COUNT
FROM ASSET_MST a
JOIN ASSET_TYPE_CD t ON a.ASSET_TYPE = t.ASSET_TYPE
WHERE a.DEL_YN = 'N'
  AND a.DISPOSE_YN = 'N'
GROUP BY a.FAMILY_ID, a.ASSET_TYPE, t.ASSET_TYPE_NM;
