-- =====================================================
-- HOMES 정기수입/지출 관리 SQL
-- charset: utf8mb4
-- =====================================================

-- 1. 현금흐름 유형 코드 테이블
--    FLOW_CATEGORY: 'INCOME'(수입) or 'EXPENSE'(지출)
CREATE TABLE IF NOT EXISTS CASH_FLOW_TYPE_CD (
    PLAN_TYPE      VARCHAR(30)  NOT NULL PRIMARY KEY,
    FLOW_CATEGORY  VARCHAR(10)  NOT NULL COMMENT 'INCOME / EXPENSE',
    PLAN_TYPE_NM   VARCHAR(100) NOT NULL,
    SORT_ORDER     INT          NOT NULL DEFAULT 0,
    USE_YN         CHAR(1)      NOT NULL DEFAULT 'Y',
    REG_DT         DATETIME     NOT NULL DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 지출 유형 초기 데이터
INSERT INTO CASH_FLOW_TYPE_CD (PLAN_TYPE, FLOW_CATEGORY, PLAN_TYPE_NM, SORT_ORDER) VALUES
('EXP_UTIL',     'EXPENSE', '공과금',       10),
('EXP_LOAN_INT', 'EXPENSE', '대출이자',     20),
('EXP_RENT',     'EXPENSE', '월세/임대료',  30),
('EXP_TELECOM',  'EXPENSE', '구독/통신',    40),
('EXP_INSURANCE','EXPENSE', '보험료',       50),
('EXP_SAVING',   'EXPENSE', '저축/적금',    60),
('EXP_EDU',      'EXPENSE', '교육비',       70),
('EXP_LIVING',   'EXPENSE', '생활비',       80),
('EXP_TRANSPORT','EXPENSE', '교통/자동차',  90),
('EXP_ETC',      'EXPENSE', '기타지출',     99)
ON DUPLICATE KEY UPDATE PLAN_TYPE_NM = VALUES(PLAN_TYPE_NM);

-- 수입 유형 초기 데이터
INSERT INTO CASH_FLOW_TYPE_CD (PLAN_TYPE, FLOW_CATEGORY, PLAN_TYPE_NM, SORT_ORDER) VALUES
('INC_SALARY',   'INCOME', '월급/급여',   10),
('INC_DIVIDEND', 'INCOME', '배당금',      20),
('INC_SIDE',     'INCOME', '부업/사이드', 30),
('INC_ALLOWANCE','INCOME', '용돈(받는)',  40),
('INC_INTEREST', 'INCOME', '이자수입',    50),
('INC_BONUS',    'INCOME', '상여/떡값',   60),
('INC_ETC',      'INCOME', '기타수입',    99)
ON DUPLICATE KEY UPDATE PLAN_TYPE_NM = VALUES(PLAN_TYPE_NM);

-- 2. CASH_FLOW_PLAN_MST 컬럼 추가
--    (이미 존재하는 컬럼 추가 시 오류 무시)
ALTER TABLE CASH_FLOW_PLAN_MST
    ADD COLUMN IF NOT EXISTS PLAN_TYPE     VARCHAR(30)  AFTER PLAN_NM,
    ADD COLUMN IF NOT EXISTS CYCLE_NUM     INT          NOT NULL DEFAULT 1 AFTER CYCLE_TYPE,
    ADD COLUMN IF NOT EXISTS CYCLE_UNIT    VARCHAR(10)  NOT NULL DEFAULT 'MONTH' AFTER CYCLE_NUM COMMENT 'DAY/MONTH/YEAR',
    ADD COLUMN IF NOT EXISTS CYCLE_BASE_DAY   INT       AFTER CYCLE_UNIT COMMENT '기준일 (예: 25일)',
    ADD COLUMN IF NOT EXISTS CYCLE_BASE_MONTH INT       AFTER CYCLE_BASE_DAY COMMENT '기준월 (예: 3월, YEAR 단위일 때)',
    ADD COLUMN IF NOT EXISTS DEL_YN        CHAR(1)      NOT NULL DEFAULT 'N' AFTER USE_YN;

-- PLAN_TYPE FK (오류 시 무시 — 코드 조인으로 처리)
ALTER TABLE CASH_FLOW_PLAN_MST
    ADD CONSTRAINT FK_CASH_FLOW_PLAN_TYPE
        FOREIGN KEY (PLAN_TYPE) REFERENCES CASH_FLOW_TYPE_CD(PLAN_TYPE);

-- LOAN_SEQ 컬럼 추가 (대출 유형 지출에 연결되는 대출 원장 SEQ)
ALTER TABLE CASH_FLOW_PLAN_MST
    ADD COLUMN IF NOT EXISTS LOAN_SEQ BIGINT AFTER COST_CENTER_SEQ;

-- 생활비 전체 연동 플래그 (Y이면 기준정보 합계와 자동 동기화)
ALTER TABLE CASH_FLOW_PLAN_MST
    ADD COLUMN IF NOT EXISTS LIVING_TOTAL_LINK_YN CHAR(1) NOT NULL DEFAULT 'N' AFTER LOAN_SEQ;

-- 인덱스
CREATE INDEX IF NOT EXISTS IDX_CASH_FLOW_PLAN_FAMILY
    ON CASH_FLOW_PLAN_MST (FAMILY_ID, FLOW_TYPE, DEL_YN, USE_YN);

-- 3. V_CASH_FLOW_EXPENSE: 정기지출 목록 뷰
CREATE OR REPLACE VIEW V_CASH_FLOW_EXPENSE AS
SELECT
    p.PLAN_SEQ,
    p.FAMILY_ID,
    p.PLAN_NM,
    p.PLAN_TYPE,
    t.PLAN_TYPE_NM,
    p.FLOW_TYPE,
    p.AMOUNT,
    p.CYCLE_NUM,
    p.CYCLE_UNIT,
    p.CYCLE_BASE_DAY,
    p.CYCLE_BASE_MONTH,
    CONCAT(
        '매 ', p.CYCLE_NUM,
        CASE p.CYCLE_UNIT WHEN 'DAY' THEN '일' WHEN 'MONTH' THEN '개월' WHEN 'YEAR' THEN '년' ELSE '' END,
        CASE
            WHEN p.CYCLE_UNIT = 'YEAR'  AND p.CYCLE_BASE_MONTH IS NOT NULL
                THEN CONCAT(' ', p.CYCLE_BASE_MONTH, '월')
            ELSE ''
        END,
        CASE WHEN p.CYCLE_BASE_DAY IS NOT NULL THEN CONCAT(' ', p.CYCLE_BASE_DAY, '일') ELSE '' END
    ) AS CYCLE_DESC,
    p.START_YMD,
    p.END_YMD,
    p.COST_CENTER_TYPE,
    p.COST_CENTER_SEQ,
    p.LOAN_SEQ,
    p.LIVING_TOTAL_LINK_YN,
    p.USE_YN,
    p.DEL_YN,
    p.MEMO,
    p.REG_ID,
    p.REG_DT,
    p.UPD_ID,
    p.UPD_DT,
    DATE_FORMAT(p.UPD_DT, '%Y-%m-%d') AS UPD_DT_STR
FROM CASH_FLOW_PLAN_MST p
LEFT JOIN CASH_FLOW_TYPE_CD t ON p.PLAN_TYPE = t.PLAN_TYPE
WHERE p.FLOW_TYPE IN ('EXPENSE', 'SAVING', 'INVEST');

-- 4. V_CASH_FLOW_INCOME: 정기수입 목록 뷰
CREATE OR REPLACE VIEW V_CASH_FLOW_INCOME AS
SELECT
    p.PLAN_SEQ,
    p.FAMILY_ID,
    p.PLAN_NM,
    p.PLAN_TYPE,
    t.PLAN_TYPE_NM,
    p.FLOW_TYPE,
    p.AMOUNT,
    p.CYCLE_NUM,
    p.CYCLE_UNIT,
    p.CYCLE_BASE_DAY,
    p.CYCLE_BASE_MONTH,
    CONCAT(
        '매 ', p.CYCLE_NUM,
        CASE p.CYCLE_UNIT WHEN 'DAY' THEN '일' WHEN 'MONTH' THEN '개월' WHEN 'YEAR' THEN '년' ELSE '' END,
        CASE
            WHEN p.CYCLE_UNIT = 'YEAR'  AND p.CYCLE_BASE_MONTH IS NOT NULL
                THEN CONCAT(' ', p.CYCLE_BASE_MONTH, '월')
            ELSE ''
        END,
        CASE WHEN p.CYCLE_BASE_DAY IS NOT NULL THEN CONCAT(' ', p.CYCLE_BASE_DAY, '일') ELSE '' END
    ) AS CYCLE_DESC,
    p.START_YMD,
    p.END_YMD,
    p.USE_YN,
    p.DEL_YN,
    p.MEMO,
    p.REG_ID,
    p.REG_DT,
    p.UPD_ID,
    p.UPD_DT,
    DATE_FORMAT(p.UPD_DT, '%Y-%m-%d') AS UPD_DT_STR
FROM CASH_FLOW_PLAN_MST p
LEFT JOIN CASH_FLOW_TYPE_CD t ON p.PLAN_TYPE = t.PLAN_TYPE
WHERE p.FLOW_TYPE = 'INCOME';
