-- =====================================================
-- HOMES 생활비 관리 SQL
-- charset: utf8mb4
-- =====================================================

-- 1. 생활비 카테고리
CREATE TABLE IF NOT EXISTS LIVING_BUDGET_CAT (
    CAT_SEQ    BIGINT       AUTO_INCREMENT PRIMARY KEY,
    FAMILY_ID  VARCHAR(30)  NOT NULL,
    CAT_NM     VARCHAR(100) NOT NULL,
    SORT_ORDER INT          NOT NULL DEFAULT 0,
    USE_YN     CHAR(1)      NOT NULL DEFAULT 'Y',
    REG_ID     VARCHAR(30),
    REG_DT     DATETIME     NOT NULL DEFAULT NOW(),
    UPD_ID     VARCHAR(30),
    UPD_DT     DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IF NOT EXISTS IDX_LIVING_CAT_FAMILY ON LIVING_BUDGET_CAT (FAMILY_ID, USE_YN);

-- 2. 생활비 항목 (기준정보)
CREATE TABLE IF NOT EXISTS LIVING_BUDGET_ITEM (
    ITEM_SEQ        BIGINT       AUTO_INCREMENT PRIMARY KEY,
    FAMILY_ID       VARCHAR(30)  NOT NULL,
    CAT_SEQ         BIGINT       NOT NULL,
    ITEM_NM         VARCHAR(100) NOT NULL,
    BUDGET_AMT      BIGINT       NOT NULL DEFAULT 0,
    INCOME_PLAN_SEQ BIGINT       COMMENT 'FK → CASH_FLOW_PLAN_MST (수입원)',
    SORT_ORDER      INT          NOT NULL DEFAULT 0,
    USE_YN          CHAR(1)      NOT NULL DEFAULT 'Y',
    DEL_YN          CHAR(1)      NOT NULL DEFAULT 'N',
    MEMO            VARCHAR(500),
    REG_ID          VARCHAR(30),
    REG_DT          DATETIME     NOT NULL DEFAULT NOW(),
    UPD_ID          VARCHAR(30),
    UPD_DT          DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IF NOT EXISTS IDX_LIVING_ITEM_FAMILY ON LIVING_BUDGET_ITEM (FAMILY_ID, CAT_SEQ, DEL_YN);

-- 비용센터 연결 컬럼 추가 (기존 테이블에 ALTER 필요)
-- ALTER TABLE LIVING_BUDGET_ITEM ADD COLUMN CC_SEQ BIGINT NULL COMMENT 'FK → COST_CENTER_MST (수입원 비용센터)' AFTER INCOME_PLAN_SEQ;

-- 5. 월별 수입 수기 등록
CREATE TABLE IF NOT EXISTS LIVING_INCOME_MST (
    INCOME_SEQ  BIGINT       AUTO_INCREMENT PRIMARY KEY,
    FAMILY_ID   VARCHAR(30)  NOT NULL,
    CC_SEQ      BIGINT       NOT NULL               COMMENT 'FK → COST_CENTER_MST',
    INCOME_YYMM CHAR(6)      NOT NULL               COMMENT '년월 YYYYMM',
    ACTUAL_AMT  BIGINT       NOT NULL DEFAULT 0     COMMENT '실제 수입금액',
    MEMO        VARCHAR(500),
    REG_ID      VARCHAR(30),
    REG_DT      DATETIME     NOT NULL DEFAULT NOW(),
    UPD_ID      VARCHAR(30),
    UPD_DT      DATETIME,
    UNIQUE KEY UK_LIVING_INCOME (FAMILY_ID, CC_SEQ, INCOME_YYMM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IF NOT EXISTS IDX_LIVING_INCOME_FAMILY ON LIVING_INCOME_MST (FAMILY_ID, INCOME_YYMM);

-- 3. 월별 생활비 실적 헤더
CREATE TABLE IF NOT EXISTS LIVING_EXPENSE_MST (
    EXP_SEQ   BIGINT      AUTO_INCREMENT PRIMARY KEY,
    FAMILY_ID VARCHAR(30) NOT NULL,
    EXP_YYMM  CHAR(6)     NOT NULL COMMENT '년월 YYYYMM',
    MEMO      VARCHAR(500),
    REG_ID    VARCHAR(30),
    REG_DT    DATETIME    NOT NULL DEFAULT NOW(),
    UPD_ID    VARCHAR(30),
    UPD_DT    DATETIME,
    UNIQUE KEY UK_LIVING_EXP (FAMILY_ID, EXP_YYMM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. 월별 생활비 실적 상세 (항목별 실제 지출)
CREATE TABLE IF NOT EXISTS LIVING_EXPENSE_DTL (
    DTL_SEQ    BIGINT  AUTO_INCREMENT PRIMARY KEY,
    EXP_SEQ    BIGINT  NOT NULL,
    ITEM_SEQ   BIGINT  NOT NULL,
    ACTUAL_AMT BIGINT  NOT NULL DEFAULT 0,
    MEMO       VARCHAR(500),
    REG_ID     VARCHAR(30),
    REG_DT     DATETIME NOT NULL DEFAULT NOW(),
    UPD_ID     VARCHAR(30),
    UPD_DT     DATETIME,
    UNIQUE KEY UK_LIVING_DTL (EXP_SEQ, ITEM_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 기준정보 초기 데이터 예시 (가족ID는 실제 값으로 변경 필요)
-- INSERT INTO LIVING_BUDGET_CAT (FAMILY_ID, CAT_NM, SORT_ORDER) VALUES ('FAM001', '서비스이용', 10);
-- INSERT INTO LIVING_BUDGET_CAT (FAMILY_ID, CAT_NM, SORT_ORDER) VALUES ('FAM001', '생활비', 20);
-- INSERT INTO LIVING_BUDGET_CAT (FAMILY_ID, CAT_NM, SORT_ORDER) VALUES ('FAM001', '공과금', 30);
-- INSERT INTO LIVING_BUDGET_CAT (FAMILY_ID, CAT_NM, SORT_ORDER) VALUES ('FAM001', '통신비', 40);
-- INSERT INTO LIVING_BUDGET_CAT (FAMILY_ID, CAT_NM, SORT_ORDER) VALUES ('FAM001', '대출/이자', 50);
-- INSERT INTO LIVING_BUDGET_CAT (FAMILY_ID, CAT_NM, SORT_ORDER) VALUES ('FAM001', '투자', 60);
-- INSERT INTO LIVING_BUDGET_CAT (FAMILY_ID, CAT_NM, SORT_ORDER) VALUES ('FAM001', '저축', 70);
