CREATE TABLE IF NOT EXISTS note_mst (
    NOTE_SEQ  BIGINT AUTO_INCREMENT PRIMARY KEY,
    FAMILY_ID VARCHAR(50)  NOT NULL,
    TITLE     VARCHAR(200) NOT NULL,
    DEL_YN    CHAR(1)      NOT NULL DEFAULT 'N',
    REG_ID    VARCHAR(50)  NOT NULL,
    REG_DT    DATETIME     NOT NULL DEFAULT NOW(),
    UPD_ID    VARCHAR(50)  NOT NULL,
    UPD_DT    DATETIME     NOT NULL DEFAULT NOW(),
    INDEX IDX_NOTE_MST_FAMILY (FAMILY_ID, DEL_YN, UPD_DT)
);

CREATE TABLE IF NOT EXISTS note_dtl (
    FAMILY_ID VARCHAR(50) NOT NULL,
    NOTE_SEQ  BIGINT      NOT NULL,
    CONTENT   LONGTEXT    NOT NULL,
    PRIMARY KEY (FAMILY_ID, NOTE_SEQ),
    CONSTRAINT FK_NOTE_DTL_MST
        FOREIGN KEY (NOTE_SEQ)
        REFERENCES note_mst (NOTE_SEQ)
        ON DELETE CASCADE
);
