-- 웹 푸시 구독 정보 테이블
-- MariaDB에서 직접 실행하세요.
CREATE TABLE PUSH_SUBSCRIPTION (
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    FAMILY_ID VARCHAR(50)  NOT NULL,
    USER_ID   VARCHAR(50)  NOT NULL,
    USER_AUTH VARCHAR(20),
    ENDPOINT  TEXT         NOT NULL,
    P256DH    VARCHAR(255) NOT NULL,
    AUTH_KEY  VARCHAR(100) NOT NULL,
    REG_DT    DATETIME     DEFAULT NOW(),
    UPD_DT    DATETIME     DEFAULT NOW() ON UPDATE NOW(),
    UNIQUE KEY UQ_PUSH_USER (FAMILY_ID, USER_ID)
);
