-- =====================================================
-- HOMES 전표처리(월 마감) 히스토리 테이블
-- charset: utf8mb4
-- =====================================================

-- 1. 비용센터 월별 스냅샷
CREATE TABLE IF NOT EXISTS COST_CENTER_HST (
    HST_SEQ        BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FAMILY_ID      VARCHAR(50)  NOT NULL,
    HST_YYMM       CHAR(6)      NOT NULL COMMENT '202504',
    CC_SEQ         BIGINT       NOT NULL,
    CC_NM          VARCHAR(200) NOT NULL,
    CC_TYPE        VARCHAR(20)  NOT NULL,
    INCOME_PLAN_NM VARCHAR(200),
    INCOME_AMT     BIGINT       NOT NULL DEFAULT 0,
    EXPENSE_AMT    BIGINT       NOT NULL DEFAULT 0,
    BALANCE        BIGINT       NOT NULL DEFAULT 0,
    REG_DT         DATETIME     NOT NULL DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IF NOT EXISTS IDX_CC_HST ON COST_CENTER_HST (FAMILY_ID, HST_YYMM);

-- 2. 자산 월별 스냅샷
CREATE TABLE IF NOT EXISTS ASSET_HST (
    HST_SEQ       BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FAMILY_ID     VARCHAR(50)  NOT NULL,
    HST_YYMM      CHAR(6)      NOT NULL,
    ASSET_SEQ     BIGINT       NOT NULL,
    ASSET_NM      VARCHAR(200) NOT NULL,
    ASSET_TYPE    VARCHAR(30)  NOT NULL,
    ASSET_TYPE_NM VARCHAR(100),
    LIQUID_YN     CHAR(1)      NOT NULL DEFAULT 'Y',
    AMOUNT        BIGINT       NOT NULL DEFAULT 0,
    REG_DT        DATETIME     NOT NULL DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IF NOT EXISTS IDX_ASSET_HST ON ASSET_HST (FAMILY_ID, HST_YYMM);

-- 3. 대출 월별 스냅샷
CREATE TABLE IF NOT EXISTS LOAN_HST (
    HST_SEQ         BIGINT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FAMILY_ID       VARCHAR(50)    NOT NULL,
    HST_YYMM        CHAR(6)        NOT NULL,
    LOAN_SEQ        BIGINT         NOT NULL,
    LOAN_NM         VARCHAR(200)   NOT NULL,
    LOAN_AMOUNT     BIGINT         NOT NULL DEFAULT 0,
    CURRENT_BALANCE BIGINT         NOT NULL DEFAULT 0,
    INTEREST_RATE   DECIMAL(5,2),
    REG_DT          DATETIME       NOT NULL DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IF NOT EXISTS IDX_LOAN_HST ON LOAN_HST (FAMILY_ID, HST_YYMM);

-- 4. 정기수입/지출 계획 월별 스냅샷
CREATE TABLE IF NOT EXISTS CASHFLOW_PLAN_HST (
    HST_SEQ      BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FAMILY_ID    VARCHAR(50)  NOT NULL,
    HST_YYMM     CHAR(6)      NOT NULL,
    PLAN_SEQ     BIGINT       NOT NULL,
    PLAN_NM      VARCHAR(200) NOT NULL,
    FLOW_TYPE    VARCHAR(20)  NOT NULL,
    PLAN_TYPE_NM VARCHAR(100),
    AMOUNT       BIGINT       NOT NULL DEFAULT 0,
    USE_YN       CHAR(1)      NOT NULL DEFAULT 'Y',
    REG_DT       DATETIME     NOT NULL DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IF NOT EXISTS IDX_CASHFLOW_PLAN_HST ON CASHFLOW_PLAN_HST (FAMILY_ID, HST_YYMM, FLOW_TYPE);
